version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_NAME: "${DB_NAME}"
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASS}"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    volumes:
      - mysql-db-volume:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    restart: always
    ports:
      - '9090:8080'
    depends_on:
      - mysqldb

volumes:
  mysql-db-volume:
